services:
  - type: web
    name: btsmt-academy
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run btsmtacademy.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: BTSMT_ADMIN_PASSWORD
        sync: false
      - key: BTSMT_DIRECTION_PASSWORD
        sync: false
      - key: BTSMT_STUDENT_EMAIL
        sync: false
      - key: BTSMT_STUDENT_PASSWORD
        sync: false
      - key: BTSMT_GUEST_EMAIL
        sync: false
      - key: BTSMT_GUEST_PASSWORD
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: BTSMT_PROF_CONTROLE_PASSWORD
        sync: false
      - key: BTSMT_PROF_INFORMATIQUE_PASSWORD
        sync: false
      - key: BTSMT_PROF_MARKETING_PASSWORD
        sync: false
      - key: BTSMT_PROF_COMMERCIALISATION_PASSWORD
        sync: false
      - key: BTSMT_PROF_COMMUNICATION_PASSWORD
        sync: false
      - key: BTSMT_PROF_ENTREPRENEURIAT_PASSWORD
        sync: false
      - key: BTSMT_PROF_ANGLAIS_PASSWORD
        sync: false
      - key: BTSMT_PROF_ARABE_PASSWORD
        sync: false
      - key: BTSMT_PROF_ESPAGNOL_PASSWORD
        sync: false
      - key: BTSMT_PROF_FRANCAIS_PASSWORD
        sync: false
      - key: BTSMT_PROF_ECONOMIE_PASSWORD
        sync: false
      - key: BTSMT_PROF_MANAGEMENT_PASSWORD
        sync: false
      - key: BTSMT_PROF_DROIT_PASSWORD
        sync: false
